/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cpuInfo */

#ifndef _Included_cpuInfo
#define _Included_cpuInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cpuInfo
 * Method:    coreCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cpuInfo_coreCount
  (JNIEnv *, jobject);

/*
 * Class:     cpuInfo
 * Method:    getModel
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cpuInfo_getModel
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
