/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sysInfo */

#ifndef _Included_sysInfo
#define _Included_sysInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sysInfo
 * Method:    intExample
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_sysInfo_intExample
  (JNIEnv *, jobject, jint);

/*
 * Class:     sysInfo
 * Method:    stringExample
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_sysInfo_stringExample
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
