/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class usbInfo */

#ifndef _Included_usbInfo
#define _Included_usbInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     usbInfo
 * Method:    read
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_usbInfo_read
  (JNIEnv *, jobject);

/*
 * Class:     usbInfo
 * Method:    busCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_usbInfo_busCount
  (JNIEnv *, jobject);

/*
 * Class:     usbInfo
 * Method:    deviceCount
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_usbInfo_deviceCount
  (JNIEnv *, jobject, jint);

/*
 * Class:     usbInfo
 * Method:    vendorID
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_usbInfo_vendorID
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     usbInfo
 * Method:    productID
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_usbInfo_productID
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
